// AUTO-GENERATED by gen_spec.py from appendices/model + appendices/contracts + FP_*_Detailed_Design v4.6/v4.5
// Source package: FP-DETAILED-1.1 (2026-09-13). Do not edit by hand.
// Feature 등록 사전(FRI v1.3 184 + OPA v1.1 249) 메타데이터.
// 제품에는 문서 원문 JSON을 두지 않는다 — 이 모듈이 값을 그대로 갖는다.
import type { SpecFriGroup, SpecOpaObject, SpecPhase } from './specTypes';

export const SPEC_FRI_PHASE_POLICY = "제안: 최초 초안 정책은 기존 구현의 필수 입력과 구분하며 Owner 승인 필요";
export const SPEC_FRI_GROUP_TOTAL = 433;
export const SPEC_OPA_FIELD_TOTAL = 249;
export const SPEC_FRI_GROUPS: SpecFriGroup[] = [
{"id":"G01","title":"식별·버전·관리 범위","owner":"Registry / Feature Owner","storage":"FeatureMaster · FeatureVersion","intro":"기능의 지속적 정체성, 정확 버전, 동시성 번호를 구분한다. 코드 이름은 통합 속성 사전의 제안명이며 실제 API 필드 대응은 별도로 본다.","dictionary":"FRI"},
{"id":"G02","title":"기능 의미·동작·경계","owner":"Feature Owner / 시스템 설계","storage":"FeatureVersion · 기능 요구 참조","intro":"등록자는 기능의 목적과 범위를 설명한다. 상세 알고리즘과 모든 구현 변수는 연결된 요구·설계에서 관리한다.","dictionary":"FRI"},
{"id":"G03","title":"분류·책임·거버넌스","owner":"Feature Owner / 기준정보·권한 관리","storage":"FeatureVersion · 조직·분류 참조","intro":"업무 담당자와 시스템 작성 이력을 구분하고, 승인된 분류·권한 기준을 참조한다.","dictionary":"FRI"},
{"id":"G04","title":"요구·제안·외부 원천 연결","owner":"Feature Owner / ALM·PLM 원천 Owner","storage":"RequirementLink · 공통 SourceRef","intro":"최초 등록에는 필요성을 설명하는 원천이 있어야 한다. 정식 요구사항 ID가 아직 없으면 제안서를 연결하고 후속 확정 대상을 기록한다.","dictionary":"FRI"},
{"id":"G05","title":"적용정보 Profile·확인 상태","owner":"Feature·Variant Owner","storage":"ApplicabilityProfile / FeatureVersion 참조","intro":"Feature 본체에는 적용정보 참조를 두고, 상세 조건과 검토 상태는 버전이 있는 연결 모델로 관리하는 방안이다.","dictionary":"FRI"},
{"id":"G06","title":"국가·차종·Trim·Variant 조건행","owner":"Variant·차량 기준정보 Owner","storage":"ConditionRow · MarketScope · Variant 참조","intro":"각 항목은 영향을 받는 경우 적용하는 조건부 속성이다. 모든 Feature에 모든 축을 강제로 채우지 않으며 독립 배열의 교차곱으로 유효 조합을 확대하지 않는다.","dictionary":"FRI"},
{"id":"G07","title":"기술 지원·구현 구성 참조","owner":"구성관리 / 차량·SW 설계","storage":"Implementation BOM · Artifact · Capability","intro":"Feature 등록에서 기술 전제를 식별하고 정확한 기술 구현 목록은 Implementation BOM에서 관리한다.","dictionary":"FRI"},
{"id":"G08","title":"Topology 관계·제약","owner":"Topology Owner / Feature Owner","storage":"RelationRecord · TopologySnapshot","intro":"관계를 하나의 자유문자 필드로 두지 않는다. 아래는 각 관계 레코드가 가져야 할 속성이다.","dictionary":"FRI"},
{"id":"G09","title":"Control Point·Flag·설정·관측","owner":"Feature Owner / Control·Vehicle 설계","storage":"ControlPoint · Binding · 실행 정책 참조","intro":"초기에는 제어 의도를 식별한다. 실행 가능한 등록·승인으로 진행할 때 실제 제어점과 바인딩을 확정한다.","dictionary":"FRI"},
{"id":"G10","title":"안전·보안·개인정보·외부 제한","owner":"각 전문 검토 Owner / Feature Owner","storage":"Assessment · Requirement · Policy 참조","intro":"관련성 및 검토 상태를 먼저 식별하고, 등급·허용 조건·검증 결과는 담당 영역의 승인된 자료를 참조한다. 아래 항목 자체가 특정 표준의 의무 목록이라는 주장은 아니다.","dictionary":"FRI"},
{"id":"G11","title":"품질속성·검증·인수","owner":"Quality / Feature Owner","storage":"QualityRequirement · TestPlan · Evidence 참조","intro":"등록에는 검증 방향을, 승인에는 해당 구성의 정확 시험·평가 근거를 연결한다.","dictionary":"FRI"},
{"id":"G12","title":"상품·운영·차량 정책 연결","owner":"Catalog / Control / Vehicle / 운영 Owner","storage":"Feature의 연결 참조·정책 요구","intro":"상품 및 운영 객체의 상세 값을 Feature 기본정보에 복제하지 않는다. 등록 단계에서는 필요한 정책 종류와 후속 연결을 식별한다.","dictionary":"FRI"},
{"id":"G13","title":"생애주기·승인·감사·자동 관리","owner":"Registry / 승인·운영 체계","storage":"FeatureVersion metadata · Audit · Approval","intro":"등록자가 직접 채우는 속성과 시스템이 생성·검증하는 정보를 분리한다.","dictionary":"FRI"},
{"id":"G14","title":"미정 사항·등록 완전성","owner":"Feature Owner / 확인 담당","storage":"OpenItem · ReadinessAssessment","intro":"미정 필드를 숨기지 않고 원천·책임·완료 시점을 관리한다. 검토 상태와 런타임 UNKNOWN은 별도 개념이다.","dictionary":"FRI"}
];

export const SPEC_OPA_OBJECTS: SpecOpaObject[] = [
{"object":"ExactRef","count":5,"fields":["OPA-001","OPA-002","OPA-003","OPA-004","OPA-005"]},
{"object":"ToolInstance","count":8,"fields":["OPA-006","OPA-007","OPA-008","OPA-009","OPA-010","OPA-011","OPA-012","OPA-013"]},
{"object":"ToolBinding","count":8,"fields":["OPA-014","OPA-015","OPA-016","OPA-017","OPA-018","OPA-019","OPA-020","OPA-021"]},
{"object":"FlagBinding","count":7,"fields":["OPA-022","OPA-023","OPA-024","OPA-025","OPA-026","OPA-027","OPA-028"]},
{"object":"ToolCapture","count":11,"fields":["OPA-029","OPA-030","OPA-031","OPA-032","OPA-033","OPA-034","OPA-035","OPA-036","OPA-037","OPA-038","OPA-039"]},
{"object":"StrategyVersion","count":9,"fields":["OPA-040","OPA-041","OPA-042","OPA-043","OPA-044","OPA-045","OPA-046","OPA-047","OPA-048"]},
{"object":"Constraint","count":5,"fields":["OPA-049","OPA-050","OPA-051","OPA-052","OPA-053"]},
{"object":"ContextSchemaVersion","count":10,"fields":["OPA-054","OPA-055","OPA-056","OPA-057","OPA-058","OPA-059","OPA-060","OPA-061","OPA-062","OPA-063"]},
{"object":"ContextValue","count":7,"fields":["OPA-064","OPA-065","OPA-066","OPA-067","OPA-068","OPA-069","OPA-070"]},
{"object":"SegmentVersion","count":7,"fields":["OPA-071","OPA-072","OPA-073","OPA-074","OPA-075","OPA-076","OPA-077"]},
{"object":"CohortProfile","count":6,"fields":["OPA-078","OPA-079","OPA-080","OPA-081","OPA-082","OPA-083"]},
{"object":"TargetSnapshot","count":8,"fields":["OPA-084","OPA-085","OPA-086","OPA-087","OPA-088","OPA-089","OPA-090","OPA-091"]},
{"object":"ResultSchemaVersion","count":7,"fields":["OPA-092","OPA-093","OPA-094","OPA-095","OPA-096","OPA-097","OPA-098"]},
{"object":"ChangeSetVersion","count":8,"fields":["OPA-099","OPA-100","OPA-101","OPA-102","OPA-103","OPA-104","OPA-105","OPA-106"]},
{"object":"QualityAssessment","count":6,"fields":["OPA-107","OPA-108","OPA-109","OPA-110","OPA-111","OPA-112"]},
{"object":"OperationalAuthorization","count":9,"fields":["OPA-113","OPA-114","OPA-115","OPA-116","OPA-117","OPA-118","OPA-119","OPA-120","OPA-121"]},
{"object":"PublicationManifest","count":14,"fields":["OPA-122","OPA-123","OPA-124","OPA-125","OPA-126","OPA-127","OPA-128","OPA-129","OPA-130","OPA-131","OPA-132","OPA-133","OPA-134","OPA-135"]},
{"object":"DecisionRecord","count":12,"fields":["OPA-136","OPA-137","OPA-138","OPA-139","OPA-140","OPA-141","OPA-142","OPA-143","OPA-144","OPA-145","OPA-146","OPA-147"]},
{"object":"RuntimeBinding","count":11,"fields":["OPA-148","OPA-149","OPA-150","OPA-151","OPA-152","OPA-153","OPA-154","OPA-155","OPA-156","OPA-157","OPA-158"]},
{"object":"NodeObservation","count":14,"fields":["OPA-159","OPA-160","OPA-161","OPA-162","OPA-163","OPA-164","OPA-165","OPA-166","OPA-167","OPA-168","OPA-169","OPA-170","OPA-171","OPA-172"]},
{"object":"CommandEnvelope","count":7,"fields":["OPA-173","OPA-174","OPA-175","OPA-176","OPA-177","OPA-178","OPA-179"]},
{"object":"AuditEvent","count":12,"fields":["OPA-180","OPA-181","OPA-182","OPA-183","OPA-184","OPA-185","OPA-186","OPA-187","OPA-188","OPA-189","OPA-190","OPA-191"]},
{"object":"RuntimeResourceProfile","count":5,"fields":["OPA-192","OPA-193","OPA-194","OPA-195","OPA-196"]},
{"object":"SafeTransitionProfile","count":7,"fields":["OPA-197","OPA-198","OPA-199","OPA-200","OPA-201","OPA-202","OPA-203"]},
{"object":"RetentionProfile","count":7,"fields":["OPA-204","OPA-205","OPA-206","OPA-207","OPA-208","OPA-209","OPA-210"]},
{"object":"CompatibilityProfile","count":12,"fields":["OPA-211","OPA-212","OPA-213","OPA-214","OPA-215","OPA-216","OPA-217","OPA-218","OPA-219","OPA-220","OPA-221","OPA-222"]},
{"object":"CanonicalPolicyVersion","count":12,"fields":["OPA-223","OPA-224","OPA-225","OPA-226","OPA-227","OPA-228","OPA-229","OPA-230","OPA-231","OPA-232","OPA-233","OPA-234"]},
{"object":"WaveVersion","count":8,"fields":["OPA-235","OPA-236","OPA-237","OPA-238","OPA-239","OPA-240","OPA-241","OPA-242"]},
{"object":"SnapshotLease","count":7,"fields":["OPA-243","OPA-244","OPA-245","OPA-246","OPA-247","OPA-248","OPA-249"]}
];

export const SPEC_FRI_PHASES: SpecPhase[] = [
{"phase":"R0","label":"최초 초안 등록","fields":["FRI-001","FRI-002","FRI-003","FRI-004","FRI-005","FRI-006","FRI-008","FRI-011","FRI-012","FRI-024","FRI-025","FRI-028","FRI-029","FRI-032","FRI-034","FRI-036","FRI-037","FRI-038","FRI-049","FRI-050","FRI-054","FRI-055","FRI-063","FRI-064","FRI-065","FRI-070","FRI-073","FRI-098","FRI-113","FRI-129","FRI-134","FRI-162","FRI-163","FRI-164","FRI-165","FRI-166","FRI-167","FRI-168","FRI-169","FRI-173","FRI-176","FRI-177","FRI-178","FRI-179","FRI-180","FRI-181","FRI-182","FRI-184"]},
{"phase":"R1","label":"기능 정의 검토","fields":["FRI-007","FRI-009","FRI-010","FRI-013","FRI-014","FRI-015","FRI-016","FRI-017","FRI-018","FRI-019","FRI-020","FRI-021","FRI-022","FRI-023","FRI-026","FRI-027","FRI-030","FRI-031","FRI-033","FRI-035","FRI-039","FRI-040","FRI-041","FRI-042","FRI-043","FRI-045","FRI-046","FRI-047","FRI-051","FRI-052","FRI-053","FRI-056","FRI-057","FRI-062","FRI-066","FRI-067","FRI-068","FRI-069","FRI-071","FRI-074","FRI-075","FRI-076","FRI-077","FRI-078","FRI-079","FRI-081","FRI-082","FRI-083","FRI-084","FRI-085","FRI-089","FRI-090","FRI-100","FRI-101","FRI-102","FRI-103","FRI-104","FRI-105","FRI-106","FRI-107","FRI-108","FRI-111","FRI-116","FRI-117","FRI-123","FRI-137","FRI-141","FRI-142","FRI-149","FRI-151","FRI-170","FRI-171","FRI-172","FRI-174","FRI-183"]},
{"phase":"R2","label":"구현·BOM 승인","fields":["FRI-044","FRI-048","FRI-058","FRI-059","FRI-060","FRI-061","FRI-072","FRI-080","FRI-086","FRI-087","FRI-088","FRI-091","FRI-092","FRI-093","FRI-094","FRI-095","FRI-096","FRI-097","FRI-099","FRI-109","FRI-110","FRI-112","FRI-114","FRI-115","FRI-118","FRI-119","FRI-120","FRI-121","FRI-122","FRI-124","FRI-125","FRI-127","FRI-130","FRI-131","FRI-133","FRI-135","FRI-136","FRI-138","FRI-139","FRI-143","FRI-144","FRI-145","FRI-146","FRI-147","FRI-148"]},
{"phase":"R3","label":"상품 발행","fields":["FRI-140","FRI-150","FRI-152","FRI-153","FRI-154","FRI-161","FRI-175"]},
{"phase":"R4","label":"차량 적용 준비","fields":["FRI-126","FRI-128","FRI-132","FRI-155","FRI-156","FRI-157","FRI-158","FRI-159","FRI-160"]}
];

/** C01-R04: R0 최초 초안 등록 단계의 필수 속성 */
export const SPEC_R0_REQUIRED: string[] = ["FRI-004","FRI-005","FRI-011","FRI-012","FRI-024","FRI-025","FRI-028","FRI-029","FRI-032","FRI-034","FRI-037","FRI-038","FRI-049","FRI-054","FRI-055","FRI-098","FRI-113","FRI-129","FRI-134","FRI-173"];
